
FROM node:12.18.2-alpine3.12

# PASSED ARGUMENTS

ARG GITHUB_AUTH_TOKEN

# WORKING DIRECTORY

WORKDIR /home/currency-reports

# COPY SOURCE FILES

COPY ./.env           ./
COPY ./.npmrc         ./
COPY ./*.json         ./
COPY ./src             /home/currency-reports/src

# SETTING UP INITIAL CONFIG

RUN echo ${GITHUB_AUTH_TOKEN} >> ./.npmrc
# So npm doesn't throw a warning/error on postinstall
RUN npm set unsafe-perm true
RUN npm ci
